import '@/styles/globals.css'
import "@/styles/inicio.css"
import "@/styles/promociones.css"
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Oxxo | A la vuelta de tu vida',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es-MX">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
